name: Update Readme and Map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Ratings"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create readme
        run: cd src && python create_readme.py

      - name: create map
        run: cd src && python create_map_data.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: update readme.md via create_readme.py
